trigger: none

variables:
- group: wiki-token
- name: site
  value: libi-devops-docs
- name: site_url
  value: libi-devops-docs.iil.intel.com
- name: namespace
  value: devops-infra
- name: k8s_connection
  value: GER Rancher (ibiuser)
- name: chart_version
  value: 0.1.0

resources:
  repositories:
    - repository: staticapp              # The alias of the repo in this pipeline
      type: git                          # A git repository
      name: DevOps/staticapp-chart       # The project/repository
      ref: refs/heads/ron                # What branch / tag to get.


jobs:
- job: azure_devops_agent
  displayName: "Build Mkdocs Site"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: Bash@3
      displayName: 'install and build mkdocs'
      inputs:
        targetType: inline
        script: |
          sudo apt install python3-pip
          pip3 install --upgrade pip && pip3 install mkdocs mkdocs-material mkdocs-material-extensions
          mkdocs build
    - task: PublishBuildArtifacts@1
      displayName: 'site publish artifact'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/site'
        artifactName: 'site'



- job: self_signed_agent
  displayName: "Deploy To Kubernetes Prod"
  dependsOn: azure_devops_agent
  pool: Development
  steps:
    - task: Kubernetes@1
      displayName: 'k8s login'
      inputs:
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: $(k8s_connection)
        command: login
    
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'

    - checkout: staticapp
    - script: |
        token=$(echo -n "pat:$(token)" | base64)
        helm upgrade $(site) . --debug --install --insecure-skip-tls-verify --namespace $(namespace) --set artifact.token="$token" --set site.url=$(site_url) --set artifact.url="$(System.TeamFoundationCollectionUri)$(System.TeamProjectId)/_apis/build/builds/$(Build.BuildId)/artifacts?artifactName=site&api-version=7.1&%24format=zip"
      displayName: 'Install or upgrade chart'

    - task: git-tag-on-release-task@9
      displayName: 'add version tag on pr to dev'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        staticTagName: '$(Build.BuildId)'
