trigger: []

variables:
- group: wiki-token
- name: site
  value: libi-devops-docs
- name: site_url
  value: libi-devops-docs.iil.intel.com
- name: namespace
  value: devops-infra
- name: k8s_connection
  value: GER Rancher (ibiuser)
- name: chart_version
  value: 0.1.0

jobs:
- job: azure_devops_agent
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: Bash@3
      displayName: 'install and build mkdocs'
      inputs:
        targetType: inline
        script: |
          sudo apt install python3-pip
          pip3 install --upgrade pip && pip3 install mkdocs mkdocs-material mkdocs-material-extensions
          mkdocs build
    - task: PublishBuildArtifacts@1
      displayName: 'site publish artifact'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/site'
        artifactName: 'site'



- job: self_signed_agent
  dependsOn: azure_devops_agent
  pool: Development
  steps:
    - task: Kubernetes@1
      displayName: 'k8s login'
      inputs:
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: $(k8s_connection)
        command: login

    - task: Bash@3
      displayName: 'kubectl apply k8s manifest'
      inputs:
        targetType: inline
        script: |
          export artifact_url='$(System.TeamFoundationCollectionUri)$(System.TeamProjectId)/_apis/build/builds/$(Build.BuildId)/artifacts?artifactName=site&api-version=7.1&%24format=zip'
          export access_token=$(echo -n "pat:$(token)" | base64)
          export site='$(site)'
          export site_url='$(site_url)'
          export namespace='$(namespace)'
          envsubst < manifest.yml | kubectl apply -f -

    - task: git-tag-on-release-task@9
      displayName: 'add version tag on pr to master'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        staticTagName: '$(Build.BuildId)'
